#!/bin/sh
#
# Cacti logo
#
#      ,*-.
#      |  |
#  ,.. |  |
#  | |_|  | ,*,
#  `---.  |_| |
#  Art |  .--`
#  by  |  |
#  kra |  |
#
# Source: https://www.asciiart.eu/plants/cactus
# Artist: kra
#
# Some adaptations were made by me in order to better
# fit the terminal and look better in color.
#

# Colors
g="${COLOR_FG_GREEN}";
p="${COLOR_FG_LPURPLE}";
t="${COLOR_FG_GREY}";

# Flowers
f="${p}*${g}"

# Logo
logo_0="${g}      ,${f}-.      "
logo_1="${g}      |  |      "
logo_2="${g}  ,.. |  |      "
logo_3="${g}  | |_|  | ,${f},  "
logo_4="${g}  \`---.  |_| |  "
logo_5="${t}  Art${g} |  .--\`   "
logo_6="${t}  by ${g} |  |      "
logo_7="${t}  kra ${g}|  |      "

# Cleanup
unset g p h f
