#!/bin/sh
#
# Fox logo
#
#    /\   /\
#   //\\_//\\   ___
#   \_'''''_/  /  /
#    / * * \  (^^^)
#    \_\./_/  |   \
#      / ^    /   /
#  Art by Todd Vargo
#
# Source: http://www.ascii-art.de/ascii/def/fox.txt
# Artist: Todd Vargo
#
# Some adaptations were made by me in order to better
# fit the terminal and look better in color.
#

# Colors
f="${COLOR_FG_BROWN}";
w="${COLOR_FG_WHITE}";
b="${COLOR_FG_LBLUE}";
g="${COLOR_FG_GREY}";

fox_logo=(
"${w}                    "
"${w}   /\   /\          "
"${f}  //\\\\\\\\_//\\\\\\\\ ${w}  ___   "
"${f}  \_'''''_/ ${w} /  /   "
"${f}   / ${b}* ${b}*${f} \  (${w}^^^${f})   "
"${f}   \_\./_/  |   \   "
"${f}     / ^    /   /   "
"${g} Art by Todd Vargo  "
)

# Cleanup
unset f w b g
