#!/bin/sh
#
# R2-D2 logo
#
#     .-""-.
#    /[0] __\
#   _|__o LI|_
#  /_| ==== |_\
#   ]|" ||  |[
#   ]|LI  o |[
#   ]|'----'|[
#  /_\ /__\ /_\
#
# Source: https://lukecod.es/static/5c6744cd9c29895e489b229b46c55516/cb011/ascii-r2d2.webp
# Artist: Luke Karrys (https://lukecod.es/)
#
# Some adaptations were made by me in order to better
# fit the terminal and look better in color.
#

# Colors
w="${COLOR_FG_WHITE}";
b="${COLOR_FG_LBLUE}";

# Shell parts (left/right)
sl="${b}]${w}"
sr="${b}[${w}"

# Blue dot
o="${b}o${w}"

logo_r2d2=(
"${w}     .-\"\"-.      "
"${w}    /${b}[0]${w} __\\     "
"${w}   _|__${o} LI|_    "
"${w}  /_| ${b}====${w} |_\\   "
"${w}   ${sl}|\" ||  |${sr}    "
"${w}   ${sl}|LI  ${o} |${sr}    "
"${w}   ${sl}|'----'|${sr}    "
"${w}  /_\\ /__\\ /_\\   "
)

# Cleanup
unset w b sl sr o
