#!/bin/sh
#
# Rainbow log
#
#        _.-'"""""'-._
#     ,-'_.-"""""""-._'-.
#    / ,' _-"""""""-_ '. \
#   | / ,'.-'"""""'-.'. \ |
#  | | / /  .'"""'.  \ \ | |
#  | | | | / ,'"', \ | | | |
#  | | | | | |   | | | | | |
#
# Artist: Samantaz Fox (me :D)
# Idea from: http://www.asciiworld.com/-Geometry-.html
#

# Colors
a="${COLOR_FG_LRED}"
b="${COLOR_FG_BROWN}"
c="${COLOR_FG_YELLOW}"
d="${COLOR_FG_LGREEN}"
e="${COLOR_FG_LBLUE}"
f="${COLOR_FG_LPURPLE}"

# Logo
logo_0=""
logo_1="  ${a}      _.-'\"\"\"\"\"'-._         "
logo_2="  ${a}   ,-'${b}_.-\"\"\"\"\"\"\"-._${a}'-.      "
logo_3="  ${a}  / ${b},' ${c}_-\"\"\"\"\"\"\"-_ ${b}'. ${a}\\     "
logo_4="  ${a} | ${b}/ ${c},'${d}.-'\"\"\"\"\"'-.${c}'. ${b}\\ ${a}|    "
logo_5="  ${a}| ${b}| ${c}/ ${d}/ ${e} ,'\"\"\"'.  ${d}\\ ${c}\\ ${b}| ${a}|   "
logo_6="  ${a}| ${b}| ${c}| ${d}| ${e}/ ${f},'\"', ${e}\\ ${d}| ${c}| ${b}| ${a}|   "
logo_7="  ${a}| ${b}| ${c}| ${d}| ${e}| ${f}|   | ${e}| ${d}| ${c}| ${b}| ${a}|   "

# Cleanup
unset a b c d e f
