#!/bin/sh
#
# Rainbow log
#
#        _.-'"""""'-._
#     ,-'_.-"""""""-._'-.
#    / ,' _-"""""""-_ '. \
#   | / ,'.-'"""""'-.'. \ |
#  | | / /  .'"""'.  \ \ | |
#  | | | | / ,'"', \ | | | |
#  | | | | | |   | | | | | |
#
# Artist: Samantaz Fox (me :D)
# Idea from: http://www.asciiworld.com/-Geometry-.html
#

# Colors
a="${COLOR_FG_LRED}"
b="${COLOR_FG_BROWN}"
c="${COLOR_FG_YELLOW}"
d="${COLOR_FG_LGREEN}"
e="${COLOR_FG_LBLUE}"
f="${COLOR_FG_LPURPLE}"

logo_rb=(
"${a}      _.-'\"\"\"\"\"'-._        "
"${a}   ,-'${b}_.-\"\"\"\"\"\"\"-._${a}'-.     "
"${a}  / ${b},' ${c}_-\"\"\"\"\"\"\"-_ ${b}'. ${a}\\    "
"${a} | ${b}/ ${c},'${d}.-'\"\"\"\"\"'-.${c}'. ${b}\\ ${a}|   "
"${a}| ${b}| ${c}/ ${d}/ ${e} ,'\"\"\"'.  ${d}\\ ${c}\\ ${b}| ${a}|  "
"${a}| ${b}| ${c}| ${d}| ${e}/ ${f},'\"', ${e}\\ ${d}| ${c}| ${b}| ${a}|  "
"${a}| ${b}| ${c}| ${d}| ${e}| ${f}|   | ${e}| ${d}| ${c}| ${b}| ${a}|  "
)

# Cleanup
unset a b c d e f
