#!/bin/sh
#
# Tux logo
#
#       __
#      *  *
#     |o_o |
#     |:_/ |
#    /    \ \
#   (|     | )
#  /'\_   _/`\
#  \___)=(___/
#
# Source: https://ascii.co.uk/art/linux
# Artist: Przemek Borys
#
# Some adaptations were made by me in order to better
# fit the terminal and look better in color.
#

# Colors
c1="${COLOR_FG_WHITE}";
c2="${COLOR_FG_DGREY}";
c3="${COLOR_FG_YELLOW}";

# Logo
logo_0="${c2}       __      "
logo_1="${c2}      *  *     "
logo_2="${c2}     |${c1}o${c2}_${c1}o${c2} |    "
logo_3="${c2}     |${c3}:_/${c2} |    "
logo_4="${c2}    /${c1}/   \\\\${c2} \\\\   "
logo_5="${c2}   (${c1}|     |${c2} )  "
logo_6="${c3}  /'\\\\_${c1}   ${c3}_/\`\\\\  "
logo_7="${c3}  \\\\___)${c2}=${c3}(___/  "

# Cleanup
unset c1 c2 c3
