#!/bin/sh
#
# Old Windows logo
#
#        _,--,_   _,--,_
#       /      / /      /
#      /      / /      /
#     /_,--,_/ /_,--,_/
#     _,--,_   _,--,_
#    /      / /      /
#   /      / /      /
#  /_,--,_/ /_,--,_/
#
# Artist: Samantaz Fox (me :D)
#

# Colors
r="${COLOR_FG_LRED}"
g="${COLOR_FG_LGREEN}"
b="${COLOR_FG_LBLUE}"
y="${COLOR_FG_YELLOW}"
n="${COLOR_NONE}"


logo_win=(
"        ${r}_,--,_${n}   ${g}_,--,_${n}  "
"       ${r}/      /${n} ${g}/      /${n} "
"      ${r}/      /${n} ${g}/      /${n}  "
"     ${r}/_,--,_/${n} ${g}/_,--,_/${n}   "
"     ${b}_,--,_${n}   ${y}_,--,_${n}     "
"    ${b}/      /${n} ${y}/      /${n}    "
"   ${b}/      /${n} ${y}/      /${n}     "
"  ${b}/_,--,_/${n} ${y}/_,--,_/${n}      "
)

# Cleanup
unset r g b y n
