#!/bin/sh

get_cpu_info()
{
	cpu_model=$1
	cpu_cores=$2
	cpu_threads=$3
}

IFS=$_new_IFS
get_cpu_info $(sysctl -n hw.model hw.ncpu kern.smp.cpus)
IFS=$_old_IFS

cpu_freq=$(sed -nE 's/^CPU:.+\(([0-9]+).+MHz.+$/\1/p' /var/run/dmesg.boot)
