#!/bin/sh

# Memory informations
get_mem_info()
{
	mem_total_kb=$1 # hw.realmem
	mem_free_kb=$2  # hw.realmem
	mem_avail_kb=$3 # hw.physmem
}

get_mem_info $(sysctl -n hw.realmem hw.physmem)


mem_total_mb=$(dc -e "$mem_total_kb 1024/ps.")
mem_free_mb=$(dc -e "$mem_free_kb 1024/ps.")
mem_avail_mb=$(dc -e "$mem_avail_kb 1024/ps.")
