#!/bin/sh

#
# Distro name
#

# Ubuntu / Debian
if [ -e /etc/lsb-release ]; then
	. /etc/lsb-release
	distro="$DISTRIB_ID $DISTRIB_RELEASE $DISTRIB_CODENAME"

# RedHat / Fedora / CentOS
elif [ -e /etc/redhat-release ]; then distro=$(cat /etc/redhat-release)
elif [ -e /etc/system-release ]; then distro=$(cat /etc/system-release)

# Arch Linux / Manjaroo
elif [ -e /etc/os-release ]; then
	. /etc/os-release
	distro="$NAME"

# Fallback
else
	distro="Linux generic"
fi


#
# Kernel / Memory / CPU details
#

_old_IFS=$IFS
IFS=$'\n'

# Kernel version
kernel="$(uname -m) $(uname -sr)"


# Memory informations
meminfo=( $(sed -nE '
	s/MemTotal:\s+([0-9]+) kB/\1/p
	s/MemFree:\s+([0-9]+) kB/\1/p
	s/MemAvailable:\s+([0-9]+) kB/\1/p
' /proc/meminfo) )

mem_total_kb="${meminfo[1]}"
mem_total_mb=$(( $mem_total_kb / 1024 ))

mem_free_kb="${meminfo[2]}"
mem_free_mb=$(( $mem_free_kb / 1024 ))

mem_avail_kb="${meminfo[3]}"
mem_avail_mb=$(( $mem_avail_kb / 1024 ))


# CPU informations
cpuinfo=( $(sed -nE '
	14q # print only the 14 first lines
	s/model name\s*:\s+(.+)(APU|CPU).*/\1\2/p
	s/cpu MHz\s+:\s+([0-9]+).*/\1/p
	s/siblings\s*:\s+([0-9]+)/\1/p
	s/cpu cores\s*:\s+([0-9]+)/\1/p
' /proc/cpuinfo) )

cpu_name="${cpuinfo[1]}"
cpu_cores="${cpuinfo[4]}"
cpu_threads="${cpuinfo[3]}"

if test -e /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq
then
	# Intel hosts, apparently
	cpu_freq=$(cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq)

	if [ ${#cpu_freq} -eq 7 ];
	then
		cpu_freq="${cpu_freq:0:1}.${cpu_freq:1:1} GHz"
	else
		cpu_freq="${cpu_freq:0:3} MHz"
	fi
else
	# Other (AMD, ARM)
	cpu_freq="${cpuinfo[2]} MHz"
fi


IFS=$_old_IFS


#
# Other
#

case $SHELL in
	*zsh)  shell=$($SHELL --version | sed -E 's/(\(.*\))//');;
	*bash) shell=$($SHELL --version | sed -E '1q');;
	*)     shell="Unknown";;
esac


disks_raw=( $(df -Ph --total --local -x tmpfs -x devtmpfs) )
disks_total=${disks_raw[-5]}
disks_used=${disks_raw[-4]}
disks_avail=${disks_raw[-3]}


if [ -e /bin/glxinfo ] || [ -e /usr/bin/glxinfo ]
then
	IFS=$'\n' glxinfo=( $( glxinfo -B | sed -nE "
		s|OpenGL vendor string: (.*)|\1|pg
		s|OpenGL renderer string: ([^/]+).*|\1|pg
	") )

	gpu_vendor="${glxinfo[1]}"
	gpu_device="${glxinfo[2]}"

	# Avoid "Intel Open Source Technology Center"
	case "$gpu_vendor" in
		Intel*)	gpu="Intel $gpu_device";;
		NVIDIA*) gpu="$gpu_vendor $gpu_device";;
	esac
else
	# Change IFS to match only newlines in lspci
	IFS=$'\n' gpu_all=( $( \
		lspci -mm | sed -nE '/VGA/{ s/(" "| "|" )/|/g; s/"$//p }'
	) )

	# Internal GPU (iGPU)
	IFS=$'|' gpu_int=( $(echo ${gpu_all[1]}) )
	gpu_int="${gpu_int[3]} $(echo "${gpu_int[4]}" | sed -nE 's/\[(.*)\]/\1/p')"

	# External GPU (graphics card)
	IFS=$'|' gpu_ext=( $(echo ${gpu_all[2]}) )
	gpu_ext="${gpu_ext[3]} $(echo "${gpu_ext[4]}" | sed -nE 's/\[(.*)\]/\1/p')"

	# Prefer external gpu
	gpu="${gpu_ext:-gpu_int}"
fi
