#!/bin/sh


# Kernel version
if [ -z "$kernel" ]; then
	kernel="$(uname -m) $(uname -sr)"
fi

# shell
case $SHELL in
	*zsh)  shell=$($SHELL --version | sed -E 's/(\(.*\))//');;
	*bash) shell=$($SHELL --version | sed -E '1s/^(GNU [Bb]ash), version ([0-9.]+).*$/\1 \2/; q');;
	*csh)  shell=$($SHELL --version | sed -E 's/^([A-Za-z0-9]+ [0-9.]+).+$/\1/');;
	*)     shell="Unknown";;
esac
