#!/bin/sh
#
# Fox logo
#
#    /\   /\
#   //\\_//\\   ___
#   \_'''''_/  /  /
#    / * * \  (^^^)
#    \_\./_/  |   \
#      / ^    /   /
#  Art by Todd Vargo
#
# Source: http://www.ascii-art.de/ascii/def/fox.txt
# Artist: Todd Vargo
#
# Some adaptations were made by me in order to better
# fit the terminal and look better in color.
#

# Colors
f="${COLOR_FG_BROWN}";
w="${COLOR_FG_WHITE}";
b="${COLOR_FG_LBLUE}";
g="${COLOR_FG_GREY}";

# Logo
logo_0="${w}                    "
logo_1="${w}   /\\\\   /\\\\          "
logo_2="${f}  //\\\\\\\\_//\\\\\\\\ ${w}  ___   "
logo_3="${f}  \\\\_'''''_/ ${w} /  /   "
logo_4="${f}   / ${b}* ${b}*${f} \\\\  (${w}^^^${f})   "
logo_5="${f}   \\\\_\\\\./_/  |   \\\\   "
logo_6="${f}     / ^    /   /   "
logo_7="${g} Art by Todd Vargo  "

# Cleanup
unset f w b g
