#!/bin/sh
#
# Old Windows logo
#
#        _,--,_   _,--,_
#       /      / /      /
#      /      / /      /
#     /_,--,_/ /_,--,_/
#     _,--,_   _,--,_
#    /      / /      /
#   /      / /      /
#  /_,--,_/ /_,--,_/
#
# Artist: Samantaz Fox (me :D)
#

# Colors
r="${COLOR_FG_LRED}"
g="${COLOR_FG_LGREEN}"
b="${COLOR_FG_LBLUE}"
y="${COLOR_FG_YELLOW}"
n="${COLOR_NONE}"

# Logo
logo_0="        ${r}_,--,_${n}   ${g}_,--,_${n}  "
logo_1="       ${r}/      /${n} ${g}/      /${n} "
logo_2="      ${r}/      /${n} ${g}/      /${n}  "
logo_3="     ${r}/_,--,_/${n} ${g}/_,--,_/${n}   "
logo_4="     ${b}_,--,_${n}   ${y}_,--,_${n}     "
logo_5="    ${b}/      /${n} ${y}/      /${n}    "
logo_6="   ${b}/      /${n} ${y}/      /${n}     "
logo_7="  ${b}/_,--,_/${n} ${y}/_,--,_/${n}      "

# Cleanup
unset r g b y n
