#!/bin/bash
#
# exif
#
# Exif data related commands
# Based on imagemagick' identify and mogrify tools
#
# Copyright 2019 (c) Samantaz
#


function exif
{
	if [[ "$1" == "show" ]]; then
		# Print the content of the exif metadata
		identify -verbose "$2" | grep "exif";
	elif [[ "$1" == "rm" ]]; then
		# Remove exif metadatas
		mogrify -strip "$2";
	else
		echo "Usage:"
		echo "exif show <file>      show the EXIF data contained in <file>"
		echo "exif rm <file>        deletes all the EXIF data in <file>"
	fi
}
