#!/bin/bash
#
# uptime
#
# Prettier display of built-in 'uptime'
#
# Copyright 2018-2019 (c) Samantaz
#


function uptime
{
	#define regexes here
	regex_noup="s/^up\s*(.*)$/\1/"
	regex_1d1c="s/(\s?[0-9]+)(\s+)([a-z])(\w+,?)/\1\3/Ig"

	# Extract data from "/usr/bin/uptime"
	since=`/usr/bin/uptime -s`
	total=`/usr/bin/uptime -p | sed -E -e "$regex_noup" -e "$regex_1d1c"`

	echo "$total (since $since)"
}
