#!/bin/bash
#
# yt-mp3
#
# Download from YT directly to mp3
# Requires 'youtube-dl'
#
# Copyright 2018 (c) Samantaz
#


function yt-mp3
{
	oldpath="${pwd}"
	cd ~/Music/dl/

	~/.local/bin/youtube-dl \
		-x --audio-format mp3 --audio-quality 320K \
		--embed-thumbnail --metadata-from-title "%(artist)s - %(title)s" \
		--output "%(title)s.%(ext)s" "$1";

	cd $oldpath
}
